image: golang:1.20

pipelines:
  branches:
    main:
      - parallel:
          - step:
              name: EIRC-Testing-CRM
              script:
                - apt-get update && apt-get install -y zip
                - mkdir deploy
                - GOOS=linux GOARCH=amd64 go build -o deploy/crm cmd/crm/crm.go
                - zip -D -j -r deploy/crm.zip deploy/crm
                - rm -rf  /opt/atlassian/pipelines/agent/build/.bitbucket/pipelines/generated/pipeline/pipes
                - pipe: atlassian/aws-lambda-deploy:1.3.0
                  variables:
                    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                    FUNCTION_NAME: 'eirc-testing-crm'
                    COMMAND: 'update'
                    ZIP_FILE: 'deploy/crm.zip'