### GetByList
GET http://localhost:8080/crm/v1.0/accounts/types?page=1&limit=20
Accept: application/json

### GetBySingle
GET http://localhost:8080/crm/v1.0/accounts/types/f31e414a-1315-418a-bc70-45660ba212f9
Accept: application/json

### Create
POST http://localhost:8080/crm/v1.0/accounts/types
Content-Type: application/json

{
  "name": "客戶"
}

### Update
PATCH http://localhost:8080/crm/v1.0/accounts/types/f31e414a-1315-418a-bc70-45660ba212f9
Content-Type: application/json

{
  "name": "競爭對手"
}

### Delete
DELETE http://localhost:8080/crm/v1.0/accounts/types/f31e414a-1315-418a-bc70-45660ba212f9
Accept: application/json
