### GetByList
GET {{host}}/crm/v1.0/accounts?page=1&limit=20
Accept: application/json

### GetByListContacts
GET {{host}}/crm/v1.0/accounts/contacts?page=1&limit=20
Accept: application/json

### GetBySingle
GET {{host}}/crm/v1.0/accounts/cf6f654e-fb06-4740-bf03-374f32406d37
Accept: application/json

### GetBySingleContacts
GET {{host}}/crm/v1.0/accounts/contacts/cf6f654e-fb06-4740-bf03-374f32406d37
Accept: application/json

### Create
POST {{host}}/crm/v1.0/accounts
Content-Type: application/json

{
  "name": "test",
  "phone_number": "0800000000",
  "created_by": "7f5443f8-e607-4793-8370-560b8b688a61",
  "type": "法人客戶",
  "industry_id": "eb6751fe-ba8d-44f6-a92f-e2efea61793a",
  "parent_account_id": "eb6751fe-ba8d-44f6-a92f-e2efea61793a"
}

### Update
PATCH {{host}}/crm/v1.0/accounts/cf6f654e-fb06-4740-bf03-374f32406d37
Content-Type: application/json

{
  "industry_id": "b1ff0cda-c8c3-4fd6-a263-2f8cbcfe61ea",
  "updated_by": "b93bda2c-d18d-4cc4-b0ad-a57056f8fc45"
}

### Delete
DELETE {{host}}/crm/v1.0/accounts/9222cb5a-3f02-411d-b577-4372989a18a9
Accept: application/json
