### login
POST {{host}}/crm/v1.0/login
Content-Type: application/json

{
  "company_id": "00000000-0000-4000-a000-000000000000",
  "user_name": "admin",
  "password": "12345"
}

> {%
    client.global.set("accessToken", response.body.body.access_token);
%}

### GetByList
POST {{host}}/crm/v1.0/contracts/list?page=1&limit=20
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "sort": {
    "field": "account_name",
    "direction": "desc"
  },
  "filter": {
    "code": "",
    "account_name": ""
  }
}

### GetBySingle
GET {{host}}/crm/v1.0/contracts/ea6c109b-2721-470d-8e59-f2fd53440b18
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create
POST {{host}}/crm/v1.0/contracts
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "status": "草稿",
  "start_date": "2023-04-21T00:00:00Z",
  "opportunity_id": "6980e433-5d4d-4eb4-ba88-84a35cbf1c86",
  "term": 6,
  "description": "test"
}

### Update
PATCH {{host}}/crm/v1.0/contracts/2cbc0aea-b004-48a9-8073-dbf9c934b447
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "status": "已簽署",
  "start_date": "2023-06-10T00:00:00Z",
  "opportunity_id": "14ebad74-c52e-4ce1-8699-a355efcf6087",
  "term": 3,
  "description": "123"
}

### Delete
DELETE {{host}}/crm/v1.0/contracts/ecb06715-854d-4720-adaf-91a2da0f59e2
Accept: application/json
Authorization: Bearer {{accessToken}}
