
### GetByList
GET {{host}}/crm/v1.0/contracts?page=1&limit=20
Accept: application/json

### GetBySingle
GET {{host}}/crm/v1.0/contracts/ea6c109b-2721-470d-8e59-f2fd53440b18
Accept: application/json

### Create
POST {{host}}/crm/v1.0/contracts
Content-Type: application/json

{
  "status": "Draft",
  "start_date": "2023-04-21T00:00:00Z",
  "created_by": "7f5443f8-e607-4793-8370-560b8b688a61",
  "account_id": "eb6751fe-ba8d-44f6-a92f-e2efea61793a",
  "term": 6,
  "description": "test"
}

### Update
PATCH {{host}}/crm/v1.0/contracts/ea6c109b-2721-470d-8e59-f2fd53440b18
Content-Type: application/json

{
  "account_id": "52f18d90-e4c3-43cb-b9d4-f62b409e7392",
  "updated_by": "b93bda2c-d18d-4cc4-b0ad-a57056f8fc45"
}

### Delete
DELETE {{host}}/crm/v1.0/contracts/c1df0068-2a85-4a6f-900a-b5f0ed0dc8a4
Accept: application/json
