### login
POST {{host}}/crm/v1.0/login
Content-Type: application/json

{
  "company_id": "00000000-0000-4000-a000-000000000000",
  "user_name": "admin",
  "password": "12345"
}

> {%
    client.global.set("accessToken", response.body.body.access_token);
%}

### GetByList
POST {{host}}/crm/v1.0/contacts/list?page=1&limit=20
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "sort": {
    "field": "salesperson_name",
    "direction": "desc"
  },
  "filter": {
    "name": "",
    "cell_phone": "",
    "email": "",
    "salesperson_name": ""
  }
}

### GetBySingle
GET {{host}}/crm/v1.0/contacts/0985edb1-d287-45ed-99ed-924675a497f5
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create
POST {{host}}/crm/v1.0/contacts
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "ABC",
  "title": "經理",
  "phone_number": "0800000000",
  "email": "test@test.com",
  "salutation": "小姐",
  "department": "業務",
  "account_id": "ab204144-44f0-4c57-935a-3a6ca06fca00"
}

### Update
PATCH {{host}}/crm/v1.0/contacts/0985edb1-d287-45ed-99ed-924675a497f5
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "5555555555588888888",
  "title": "經理",
  "phone_number": "1111111111",
  "cell_phone": "55555",
  "salutation": "",
  "department": "業務",
  "account_id": "ab204144-44f0-4c57-935a-3a6ca06fca00"
}

### Delete
DELETE {{host}}/crm/v1.0/contacts/e5025fab-0f89-4336-8e7e-19aae6a7ffc9
Accept: application/json
Authorization: Bearer {{accessToken}}
