
### GetByList
GET http://localhost:8080/crm/v1.0/contracts?page=1&limit=20
Accept: application/json

### GetBySingle
GET http://localhost:8080/crm/v1.0/contracts/cb6da4e5-e2da-49ab-923f-7a9442ec9633
Accept: application/json

### Create
POST http://localhost:8080/crm/v1.0/contracts
Content-Type: application/json

{
  "status": "Draft",
  "start_date": "2023-04-21T00:00:00Z",
  "created_by": "eb6751fe-ba8d-44f6-a92f-e2efea61793a",
  "account_id": "eb6751fe-ba8d-44f6-a92f-e2efea61793a",
  "term": 6,
  "description": "test"
}

### Update
PATCH http://localhost:8080/crm/v1.0/contracts/cb6da4e5-e2da-49ab-923f-7a9442ec9633
Content-Type: application/json

{
  "status": "Activated",
  "updated_by": "4bdf4c46-d7e7-4025-9872-4a28da823209"
}

### Delete
DELETE http://localhost:8080/crm/v1.0/contracts/cb6da4e5-e2da-49ab-923f-7a9442ec9633
Accept: application/json
