### login
POST {{host}}/crm/v1.0/login
Content-Type: application/json

{
  "company_id": "00000000-0000-4000-a000-000000000000",
  "user_name": "admin",
  "password": "12345"
}

> {%
    client.global.set("accessToken", response.body.body.access_token);
%}

### GetByList
POST {{host}}/crm/v1.0/events/list
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "filter": {
    "subject": "",
    "main_id":"",
    "attendee_id": "",
    "type": "",
    "start_date": ""
  }
}

### GetBySingle
GET {{host}}/crm/v1.0/events/b7b4e10d-f2ef-4291-89ae-b7f1eee2f3dd
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create
POST {{host}}/crm/v1.0/events
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "subject": "bug",
  "main": [
    "85cee689-bcb2-461f-8b0a-ea6922f1cb07",
    "f1169ccc-370a-4e5e-b1e9-71fc6ccc0818"
  ],
  "attendee": [
    "85cee689-bcb2-461f-8b0a-ea6922f1cb07",
    "dbb472c9-81d5-47bc-8958-d4d097bb3597"
  ],
  "is_whole": false,
  "start_date": "2023-07-21T00:00:00Z",
  "end_date": "2023-07-21T00:00:00Z",
  "account_id": "00000000-0000-4000-a000-000000000000",
  "contact": [
    "eb243950-92b4-4433-92a7-847f000aea44",
    "3aca2139-2df0-41eb-b26b-5ee529a832b2"
  ],
  "type": "test",
  "location": "taipei",
  "description": "test"
}

### Update
PATCH {{host}}/crm/v1.0/events/06f8b683-e680-40a8-ba09-adb12f3ccc4c
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "subject": "test111111",
  "main": [
    "85cee689-bcb2-461f-8b0a-ea6922f1cb07",
    "f1169ccc-370a-4e5e-b1e9-71fc6ccc0818"
  ],
  "attendee": [
    "85cee689-bcb2-461f-8b0a-ea6922f1cb07",
    "dbb472c9-81d5-47bc-8958-d4d097bb3597"
  ],
  "is_whole": false,
  "start_date": "2023-08-01T00:00:00Z",
  "end_date": "2023-08-01T00:00:00Z",
  "account_id": "00000000-0000-4000-a000-000000000000",
  "contact": [
    "eb243950-92b4-4433-92a7-847f000aea44",
    "3aca2139-2df0-41eb-b26b-5ee529a832b2"
  ],
  "type": "test",
  "location": "taipei",
  "description": "test"
}

### Delete
DELETE {{host}}/crm/v1.0/events/9b32679e-7770-4230-9e0a-fdef1675a1a2
Accept: application/json
Authorization: Bearer {{accessToken}}
