### GetByList
GET http://localhost:8080/authority/v1.0/industries?page=1&limit=20
Accept: application/json

### GetBySingle
GET http://localhost:8080/authority/v1.0/industries/ce6fafd4-a07d-41b8-ada6-261ca90d89f6
Accept: application/json

### Create
POST http://localhost:8080/authority/v1.0/industries
Content-Type: application/json

{
  "name": "服務業"
}

### Update
PATCH http://localhost:8080/authority/v1.0/industries/ce6fafd4-a07d-41b8-ada6-261ca90d89f6
Content-Type: application/json

{
  "name": "製造業"
}

### Delete
DELETE http://localhost:8080/authority/v1.0/industries/ce6fafd4-a07d-41b8-ada6-261ca90d89f6
Accept: application/json
