### GetByList
GET http://localhost:8080/crm/v1.0/leads?page=1&limit=20
Accept: application/json

### GetBySingle
GET http://localhost:8080/crm/v1.0/leads/4feb77de-1f06-4c1c-bc48-dfe547171c1c
Accept: application/json

### Create
POST http://localhost:8080/crm/v1.0/leads
Content-Type: application/json

{
  "status": "New",
  "company_name": "Test",
  "created_by": "eb6751fe-ba8d-44f6-a92f-e2efea61793a",
  "source_id": "00000000-0000-0000-0000-000000000000",
  "industry_id": "00000000-0000-0000-0000-000000000000",
  "rating": "Hot"
}

### Update
PATCH http://localhost:8080/crm/v1.0/leads/0886af92-9bcc-4259-b3f9-bd90e1378cd3
Content-Type: application/json

{
  "status": "Working",
  "updated_by": "4bdf4c46-d7e7-4025-9872-4a28da823209"
}

### Delete
DELETE http://localhost:8080/crm/v1.0/leads/0886af92-9bcc-4259-b3f9-bd90e1378cd3
Accept: application/json
