### login
POST {{host}}/crm/v1.0/login
Content-Type: application/json

{
  "company_id": "00000000-0000-4000-a000-000000000000",
  "user_name": "admin",
  "password": "12345"
}

> {% client.global.set("accessToken", response.body.body.access_token); %}

### GetByList
POST {{host}}/crm/v1.0/leads/list?page=1&limit=20
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "sort": {
    "field": "account_name",
    "direction": "asc"
  },
  "filter": {
    "description": "",
    "account_name": "",
    "rating": "",
    "source": "",
    "status": [
      "已轉換",
      "發展中"
    ],
    "salesperson_name": ""
  }
}

### GetByListNoPagination
POST {{host}}/crm/v1.0/leads/list/no-pagination
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "filter": {
    "description": "",
    "rating": "",
    "source": "",
    "status": [
      "發展中"
    ]
  }
}

### GetBySingle
GET {{host}}/crm/v1.0/leads/4feb77de-1f06-4c1c-bc48-dfe547171c1c
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create
POST {{host}}/crm/v1.0/leads
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "status": "1",
  "description": "Test",
  "source": "展演",
  "account_id": "609efef9-d88a-4b5b-a402-f27ad0424da2",
  "rating": "Hot"
}

### Update
PATCH {{host}}/crm/v1.0/leads/7c0dd994-3501-4660-8f30-638384136382
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "status": "新線索",
  "description": "50",
  "account_id": "d6cb3bc4-474d-4932-8804-9c04ed380e1e",
  "salesperson_id": "85cee689-bcb2-461f-8b0a-ea6922f1cb07"
}

### Delete
DELETE {{host}}/crm/v1.0/leads/6e71dd81-4d33-4d9b-9e1d-c99f14ddf225
Accept: application/json
Authorization: Bearer {{accessToken}}