### login
POST {{host}}/crm/v1.0/login
Content-Type: application/json

{
  "company_id": "00000000-0000-4000-a000-000000000000",
  "user_name": "admin",
  "password": "12345"
}

> {% client.global.set("refreshToken", response.body.body.refresh_token); %}

### refresh
POST {{host}}/crm/v1.0/refresh
Content-Type: application/json

{
  "refresh_token": "{{refreshToken}}"
}

