### login
POST http://localhost:8080/authority/v1.0/login
Content-Type: application/json

{
  "company_id": "1a8e81ed-8ec7-4cba-831a-77ea4079b3fd",
  "user_name": "test",
  "password": "12345"
}

### refresh
POST http://localhost:8080/authority/v1.0/refresh
Content-Type: application/json

{
  "refresh_token": "REMOVED"
}

