### login
POST {{host}}/crm/v1.0/login
Content-Type: application/json

{
  "company_id": "00000000-0000-4000-a000-000000000000",
  "user_name": "admin",
  "password": "12345"
}

> {% client.global.set("accessToken", response.body.body.access_token); %}

### GetByList
POST {{host}}/crm/v1.0/opportunities/list?page=1&limit=20
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "sort": {
    "field": "account_name",
    "direction": "desc"
  },
  "filter": {
    "name": "虛",
    "account_name": "虛",
    "salesperson_name": "虛"
  }
}

### GetByListCampaigns
GET {{host}}/crm/v1.0/opportunities/campaigns?page=1&limit=20
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetBySingle
GET {{host}}/crm/v1.0/opportunities/373042d7-3cb4-4e17-b69f-9b294b69eb7f
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetBySingleCampaigns
GET {{host}}/crm/v1.0/opportunities/campaigns/373042d7-3cb4-4e17-b69f-9b294b69eb7f
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create
POST {{host}}/crm/v1.0/opportunities
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "test",
  "stage": "資格評估",
  "forecast_category": "結案",
  "close_date": "2023-04-27T00:00:00Z",
  "account_id": "cf6f654e-fb06-4740-bf03-374f32406d37",
  "amount": 500
}

### Update
PATCH {{host}}/crm/v1.0/opportunities/373042d7-3cb4-4e17-b69f-9b294b69eb7f
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "A"
}

### Delete
DELETE {{host}}/crm/v1.0/opportunities/fd62da01-7206-4e59-8e24-30d22c270163
Accept: application/json
Authorization: Bearer {{accessToken}}