### GetByList
GET http://localhost:8080/crm/v1.0/opportunities?page=1&limit=20
Accept: application/json

### GetBySingle
GET http://localhost:8080/crm/v1.0/opportunities/f17d8b17-35fa-4262-8495-09e56d512876
Accept: application/json

### Create
POST http://localhost:8080/crm/v1.0/opportunities
Content-Type: application/json

{
  "stage": "資格評估",
  "forecast_category": "結案",
  "created_by": "7f5443f8-e607-4793-8370-560b8b688a61",
  "close_date": "2023-04-27T00:00:00Z",
  "account_id": "cf6f654e-fb06-4740-bf03-374f32406d37",
  "amount": 500
}

### Update
PATCH http://localhost:8080/crm/v1.0/opportunities/8e4cf7ff-08ac-4772-8c1d-c5c1090649e8
Content-Type: application/json

{
  "close_date": "2023-04-27T11:00:00Z",
  "updated_by": "b93bda2c-d18d-4cc4-b0ad-a57056f8fc45"
}

### Delete
DELETE http://localhost:8080/crm/v1.0/opportunities/8e4cf7ff-08ac-4772-8c1d-c5c1090649e8
Accept: application/json
