### GetByList
GET {{host}}/crm/v1.0/opportunities?page=1&limit=20
Accept: application/json

### GetByListCampaigns
GET {{host}}/crm/v1.0/opportunities/campaigns?page=1&limit=20
Accept: application/json

### GetBySingle
GET {{host}}/crm/v1.0/opportunities/373042d7-3cb4-4e17-b69f-9b294b69eb7f
Accept: application/json

### GetBySingleCampaigns
GET {{host}}/crm/v1.0/opportunities/campaigns/373042d7-3cb4-4e17-b69f-9b294b69eb7f
Accept: application/json

### Create
POST {{host}}/crm/v1.0/opportunities
Content-Type: application/json

{
  "name": "test",
  "stage": "資格評估",
  "forecast_category": "結案",
  "created_by": "7f5443f8-e607-4793-8370-560b8b688a61",
  "close_date": "2023-04-27T00:00:00Z",
  "account_id": "cf6f654e-fb06-4740-bf03-374f32406d37",
  "amount": 500
}

### Update
PATCH {{host}}/crm/v1.0/opportunities/373042d7-3cb4-4e17-b69f-9b294b69eb7f
Content-Type: application/json

{
  "name": "A",
  "updated_by": "b93bda2c-d18d-4cc4-b0ad-a57056f8fc45"
}

### Delete
DELETE {{host}}/crm/v1.0/opportunities/fd62da01-7206-4e59-8e24-30d22c270163
Accept: application/json
