### GetByList
GET http://localhost:8080/crm/v1.0/orders/products?page=1&limit=20
Accept: application/json

### GetBySingle
GET http://localhost:8080/crm/v1.0/orders/products/f31e414a-1315-418a-bc70-45660ba212f9
Accept: application/json

### Create
POST http://localhost:8080/crm/v1.0/orders/products
Content-Type: application/json

{
  "order_id": "00000000-0000-4000-a000-000000000000",
  "product_id": "00000000-0000-4000-a000-000000000000",
  "quantity": 2,
  "unit_price": 30,
  "description": "test",
  "created_by": "eb6751fe-ba8d-44f6-a92f-e2efea61793a"
}

### Update
PATCH http://localhost:8080/crm/v1.0/orders/products/55485bf5-3d6e-4661-9e38-0d8e7086b0c6
Content-Type: application/json

{
  "unit_price": 10,
  "updated_by": "4bdf4c46-d7e7-4025-9872-4a28da823209"
}

### Delete
DELETE http://localhost:8080/crm/v1.0/orders/products/4f9d5825-7c92-484f-9eda-61f446424424
Accept: application/json
