### login
POST {{host}}/crm/v1.0/login
Content-Type: application/json

{
  "company_id": "00000000-0000-4000-a000-000000000000",
  "user_name": "admin",
  "password": "12345"
}

> {% client.global.set("accessToken", response.body.body.access_token); %}

### GetByList
GET {{host}}/crm/v1.0/orders-products?page=1&limit=20
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetBySingle
GET {{host}}/crm/v1.0/orders-products/ca473b1c-a33b-48e3-b386-b569719f3d01
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create
POST {{host}}/crm/v1.0/orders-products
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "products": [
    {
      "order_id": "e4470b2d-b3c2-4f64-a62a-c4a7b3776d44",
      "product_id": "2a795d43-6a8a-4824-8d1a-0707f6eb75e9",
      "quantity": 1,
      "unit_price": 100,
      "quote_price": 200,
      "description": "test"
    }
  ]
}

### Update
PATCH {{host}}/crm/v1.0/orders-products
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "products": [
    {
      "order_product_id": "a86f6133-b34f-4486-86a8-99084dabe744",
      "order_id": "3234b981-dcd5-42dc-b589-f35d0138f84b",
      "quantity": 2,
      "unit_price": 50,
      "description": "test",
      "product_id": "2a795d43-6a8a-4824-8d1a-0707f6eb75e9"
    }
  ]
}

### Delete
DELETE {{host}}/crm/v1.0/orders-products
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "products": [
      "a86f6133-b34f-4486-86a8-99084dabe744"
  ]
}
