### GetByList
GET {{host}}/crm/v1.0/orders?page=1&limit=20
Accept: application/json

### GetByListProducts
GET {{host}}/crm/v1.0/orders/products?page=1&limit=20
Accept: application/json

### GetBySingle
GET {{host}}/crm/v1.0/orders/be75a422-62cb-4893-952d-4c9d1f504189
Accept: application/json

### GetBySingleProducts
GET {{host}}/crm/v1.0/orders/products/be75a422-62cb-4893-952d-4c9d1f504189
Accept: application/json


### Create
POST {{host}}/crm/v1.0/orders
Content-Type: application/json

{
  "status": "草稿",
  "start_date": "2023-04-21T00:00:00Z",
  "created_by": "7f5443f8-e607-4793-8370-560b8b688a61",
  "account_id": "cf6f654e-fb06-4740-bf03-374f32406d37",
  "contract_id": "05c76ec9-070e-42a1-b54e-9f2e048e4ced",
  "description": "test"
}

### Update
PATCH {{host}}/crm/v1.0/orders/3776ecf5-9229-4a49-858f-0e89bc7be2d3
Content-Type: application/json

{
  "status": "啟動中",
  "updated_by": "b93bda2c-d18d-4cc4-b0ad-a57056f8fc45"
}

### Delete
DELETE {{host}}/crm/v1.0/orders/f6999086-d10e-4947-8a0f-da92a8bf6127
Accept: application/json
