### login
POST {{host}}/crm/v1.0/login
Content-Type: application/json

{
  "company_id": "00000000-0000-4000-a000-000000000000",
  "user_name": "admin",
  "password": "12345"
}

> {% client.global.set("accessToken", response.body.body.access_token); %}

### GetByList
POST {{host}}/crm/v1.0/orders/list?page=1&limit=20
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "sort": {
    "field": "account_name",
    "direction": "asc"
  },
  "filter": {
    "code": "",
    "account_name": "",
    "contract_code": ""
  }
}

### GetBySingle
GET {{host}}/crm/v1.0/orders/be75a422-62cb-4893-952d-4c9d1f504189
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetBySingleProducts
GET {{host}}/crm/v1.0/orders/products/be75a422-62cb-4893-952d-4c9d1f504189
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create
POST {{host}}/crm/v1.0/orders
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "status": "草稿",
  "start_date": "2023-04-21T00:00:00Z",
  "contract_id": "9f544bae-8a4c-42e6-8ec6-f7f77123fc3b",
  "description": "ABC"
}

### Update
PATCH {{host}}/crm/v1.0/orders/c17c5479-4e79-44f4-a4c7-0a86d7f2d21b
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "status": "草稿"
}

### Delete
DELETE {{host}}/crm/v1.0/orders/f6999086-d10e-4947-8a0f-da92a8bf6127
Accept: application/json
Authorization: Bearer {{accessToken}}
