### GetByList
GET {{host}}/crm/v1.0/orders-products?page=1&limit=20
Accept: application/json

### GetBySingle
GET {{host}}/crm/v1.0/orders-products/ca473b1c-a33b-48e3-b386-b569719f3d01
Accept: application/json

### Create
POST {{host}}/crm/v1.0/orders-products
Content-Type: application/json

{
  "order_id": "3234b981-dcd5-42dc-b589-f35d0138f84b",
  "product_id": "2a795d43-6a8a-4824-8d1a-0707f6eb75e9",
  "quantity": 1,
  "unit_price": 100,
  "description": "test",
  "created_by": "7f5443f8-e607-4793-8370-560b8b688a61"
}

### Update
PATCH {{host}}/crm/v1.0/orders-products/ca473b1c-a33b-48e3-b386-b569719f3d01
Content-Type: application/json

{
  "order_id": "3234b981-dcd5-42dc-b589-f35d0138f84b",
  "quantity": 2,
  "unit_price": 50,
  "description": "test",
  "product_id": "2a795d43-6a8a-4824-8d1a-0707f6eb75e9",
  "updated_by": "b93bda2c-d18d-4cc4-b0ad-a57056f8fc45"
}

### Delete
DELETE {{host}}/crm/v1.0/orders-products/cd594a2a-ab19-42b2-9751-81b11505f189
Accept: application/json
