### GetAllPolicies
GET {{host}}/crm/v1.0/policies
Accept: application/json

### AddPolicy
POST {{host}}/crm/v1.0/policies
Content-Type: application/json

{
  "ptype": "p",
  "role_name": "admin",
  "path": "/crm/v1.0/users",
  "method": "POST"
}

### DeletePolicy
DELETE {{host}}/crm/v1.0/policies
Content-Type: application/json

{
  "ptype": "p",
  "role_name": "admin",
  "path": "/crm/v1.0/users",
  "method": "post"
}
