### GetByList
GET http://localhost:8080/crm/v1.0/products?page=1&limit=20
Accept: application/json

### GetBySingle
GET http://localhost:8080/crm/v1.0/products/bd12125b-6d35-468f-b95f-a184c0ab89d6
Accept: application/json

### Create
POST http://localhost:8080/crm/v1.0/products
Content-Type: application/json

{
  "name": "test",
  "code": "test123",
  "is_enable": true,
  "created_by": "eb6751fe-ba8d-44f6-a92f-e2efea61793a",
  "description": "test"
}

### Update
PATCH http://localhost:8080/crm/v1.0/products/bd12125b-6d35-468f-b95f-a184c0ab89d6
Content-Type: application/json

{
  "code": "test321",
  "updated_by": "4bdf4c46-d7e7-4025-9872-4a28da823209"
}

### Delete
DELETE http://localhost:8080/crm/v1.0/products/b412839d-4fff-49c0-bdf4-24b75afaf282
Accept: application/json
