### GetByList
GET http://localhost:8080/crm/v1.0/products?page=1&limit=20
Accept: application/json

### GetBySingle
GET http://localhost:8080/crm/v1.0/products/67506062-59ea-449f-afba-f85ae2cbfaa5
Accept: application/json

### Create
POST http://localhost:8080/crm/v1.0/products
Content-Type: application/json

{
  "name": "test",
  "code": "test123",
  "is_enable": true,
  "created_by": "eb6751fe-ba8d-44f6-a92f-e2efea61793a",
  "description": "test",
  "price": 100
}

### Update
PATCH http://localhost:8080/crm/v1.0/products/67506062-59ea-449f-afba-f85ae2cbfaa5
Content-Type: application/json

{
  "price": 50,
  "updated_by": "4bdf4c46-d7e7-4025-9872-4a28da823209"
}

### Delete
DELETE http://localhost:8080/crm/v1.0/products/67506062-59ea-449f-afba-f85ae2cbfaa5
Accept: application/json
