### login
POST {{host}}/crm/v1.0/login
Content-Type: application/json

{
  "company_id": "00000000-0000-4000-a000-000000000000",
  "user_name": "admin",
  "password": "12345"
}

> {% client.global.set("accessToken", response.body.body.access_token); %}

### GetByList
POST {{host}}/crm/v1.0/products/list?page=1&limit=20
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "sort": {
    "field": "code",
    "direction": "asc"
  },
  "filter": {
    "description": "",
    "name": "",
    "code": ""
  }
}

### GetBySingle
GET {{host}}/crm/v1.0/products/67506062-59ea-449f-afba-f85ae2cbfaa5
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create
POST {{host}}/crm/v1.0/products
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "test",
  "code": "test123",
  "is_enable": true,
  "description": "test",
  "price": 50
}

### Update
PATCH {{host}}/crm/v1.0/products/faf53183-1a71-41d4-9a66-8100a55842b0
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "test",
  "code": "test123",
  "is_enable": false,
  "description": "test",
  "price": 100
}

### Delete
DELETE {{host}}/crm/v1.0/products/1a22b43a-cdd1-40e0-9247-b6fd4a0b61b6
Accept: application/json
Authorization: Bearer {{accessToken}}
