### login
POST {{host}}/crm/v1.0/login
Content-Type: application/json

{
  "company_id": "00000000-0000-4000-a000-000000000000",
  "user_name": "admin",
  "password": "12345"
}

> {% client.global.set("accessToken", response.body.body.access_token); %}

### GetByList
POST {{host}}/crm/v1.0/quotes/list?page=1&limit=20
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "sort": {
    "field": "opportunity_name",
    "direction": "desc"
  },
  "filter": {
    "name": "",
    "opportunity_name": ""
  }
}

### GetBySingle
GET {{host}}/crm/v1.0/quotes/f37d7364-cf96-47f1-a267-e0725e8295c6
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetBySingleProducts
GET {{host}}/crm/v1.0/quotes/products/f37d7364-cf96-47f1-a267-e0725e8295c6
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetByOpportunityIDSingle
GET {{host}}/crm/v1.0/quotes/get-by-opportunity/00000000-0000-4000-a000-000000000000
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create
POST {{host}}/crm/v1.0/quotes
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "555",
  "status": "草稿",
  "is_syncing": false,
  "opportunity_id": "00000000-0000-4000-a000-000000000000",
  "account_id": "cf6f654e-fb06-4740-bf03-374f32406d37",
  "description": "test",
  "expiration_date": "2023-04-26T00:00:00Z",
  "tax": 50,
  "shipping_and_handling": 50
}

### Update
PATCH {{host}}/crm/v1.0/quotes/f37d7364-cf96-47f1-a267-e0725e8295c6
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "is_final": true
}

### Delete
DELETE {{host}}/crm/v1.0/quotes/28a8b00e-e30a-4fb2-954a-7e0bacbdc940
Accept: application/json
Authorization: Bearer {{accessToken}}
