### login
POST {{host}}/crm/v1.0/login
Content-Type: application/json

{
  "company_id": "00000000-0000-4000-a000-000000000000",
  "user_name": "admin",
  "password": "12345"
}

> {% client.global.set("accessToken", response.body.body.access_token); %}

### GetByList
GET {{host}}/crm/v1.0/quotes-products?page=1&limit=20
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetBySingle
GET {{host}}/crm/v1.0/quotes-products/7806a0f7-9609-4a8c-bb38-b488ea507732
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create
POST {{host}}/crm/v1.0/quotes-products
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "products": [
    {
      "quote_id": "2197d141-c820-45cf-8930-c3d80dc945d6",
      "product_id": "2a795d43-6a8a-4824-8d1a-0707f6eb75e9",
      "quantity": 1,
      "unit_price": 100,
      "discount": 50
    },
    {
      "quote_id": "2197d141-c820-45cf-8930-c3d80dc945d6",
      "product_id": "2a795d43-6a8a-4824-8d1a-0707f6eb75e9",
      "quantity": 1,
      "unit_price": 100,
      "discount": 50
    }
  ]
}

### Update
PATCH {{host}}/crm/v1.0/quotes-products
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "products": [
    {
      "quote_product_id": "8342360d-2e16-4bcf-a5ee-84473ade507d",
      "quote_id": "47f65a39-f7fb-444d-8a85-5166b8e603fa",
      "product_id": "3e374065-bba2-4ce9-964c-38303c6f4583",
      "quantity": 1,
      "unit_price": 100,
      "discount": 50
    },
    {
      "quote_product_id": "58821721-20d3-4186-a9e3-d5f5ab3db836",
      "quote_id": "47f65a39-f7fb-444d-8a85-5166b8e603fa",
      "product_id": "2a795d43-6a8a-4824-8d1a-0707f6eb75e9",
      "quantity": 1,
      "unit_price": 100,
      "discount": 50
    }
  ]
}

### Delete
DELETE {{host}}/crm/v1.0/quotes-products/a0c68ba6-cc3a-4579-8c9c-c6580ef76f2b
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "products": [
      "aa272c66-4ec3-4894-bb3f-131461cb8bb2",
      "b12d204a-5324-4de2-ab63-30e4fce43987"
  ]
}
