### login
POST {{host}}/crm/v1.0/login
Content-Type: application/json

{
  "company_id": "00000000-0000-4000-a000-000000000000",
  "user_name": "admin",
  "password": "12345"
}

> {% client.global.set("accessToken", response.body.body.access_token); %}

### GetByList
GET {{host}}/crm/v1.0/quotes-products?page=1&limit=20
Accept: application/json
Authorization: Bearer {{accessToken}}

### GetBySingle
GET {{host}}/crm/v1.0/quotes-products/d465cfe9-0b92-4528-8602-9c05ec6c5847
Accept: application/json
Authorization: Bearer {{accessToken}}

### Create
POST {{host}}/crm/v1.0/quotes-products
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "products": [
    {
      "quote_id": "5592ae6a-925d-478d-9e73-0a2984f33507",
      "product_id": "2a795d43-6a8a-4824-8d1a-0707f6eb75e9",
      "quantity": 1,
      "unit_price": 100,
      "discount": 50,
      "description": "1"
    },
    {
      "quote_id": "5592ae6a-925d-478d-9e73-0a2984f33507",
      "product_id": "2a795d43-6a8a-4824-8d1a-0707f6eb75e9",
      "quantity": 1,
      "unit_price": 100,
      "discount": 50,
      "description": "1"
    }
  ]
}

### Update
PATCH {{host}}/crm/v1.0/quotes-products
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "products": [
    {
      "quote_product_id": "d465cfe9-0b92-4528-8602-9c05ec6c5847",
      "quote_id": "47f65a39-f7fb-444d-8a85-5166b8e603fa",
      "product_id": "3e374065-bba2-4ce9-964c-38303c6f4583",
      "quantity": 20,
      "unit_price": 350,
      "discount": 5,
      "description": "1"
    }
  ]
}

### Delete
DELETE {{host}}/crm/v1.0/quotes-products
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "products": [
      "aa272c66-4ec3-4894-bb3f-131461cb8bb2",
      "b12d204a-5324-4de2-ab63-30e4fce43987"
  ]
}
