### GetByList
GET http://localhost:8080/authority/v1.0/users?page=1&limit=20
Accept: application/json

### GetBySingle
GET http://localhost:8080/authority/v1.0/users/9787e109-5724-4654-b8a9-324fed5326fe
Accept: application/json

### Create
POST http://localhost:8080/authority/v1.0/users
Content-Type: application/json
Authorization: Bearer REMOVED

{
  "user_name": "test",
  "company_id": "1a8e81ed-8ec7-4cba-831a-77ea4079b3fd",
  "created_by": "eb6751fe-ba8d-44f6-a92f-e2efea61793a",
  "email": "test@test.com",
  "name": "test",
  "password": "12345",
  "phone_number": "123",
}

### Update
PATCH http://localhost:8080/authority/v1.0/users/7b4d0504-b632-459b-bd86-761685157ac9
Content-Type: application/json

{
  "password": "54321",
  "updated_by": "4bdf4c46-d7e7-4025-9872-4a28da823209"
}

### Delete
DELETE http://localhost:8080/authority/v1.0/users/9787e109-5724-4654-b8a9-324fed5326fe
Content-Type: application/json

{
  "user_name": "deleted_test",
  "updated_by": "4bdf4c46-d7e7-4025-9872-4a28da823209"
}
