### login
POST {{host}}/crm/v1.0/login
Content-Type: application/json

{
  "company_id": "00000000-0000-4000-a000-000000000000",
  "user_name": "admin",
  "password": "12345"
}

> {% client.global.set("accessToken", response.body.body.access_token); %}

### GetByList
GET {{host}}/crm/v1.0/users?page=1&limit=20
Accept: application/json

### GetBySingle
GET {{host}}/crm/v1.0/users/9787e109-5724-4654-b8a9-324fed5326fe
Accept: application/json

### Create
POST {{host}}/crm/v1.0/users
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "user_name": "test1",
  "email": "test1@test1.com",
  "name": "test1",
  "password": "12345",
  "phone_number": "test1"
}

### Update
PATCH {{host}}/crm/v1.0/users/0c1668c9-ecd7-442c-ab94-ecefa377eec9
Content-Type: application/json

{
  "company_id": "00000000-0000-4000-a000-000000000000",
  "updated_by": "4bdf4c46-d7e7-4025-9872-4a28da823209"
}

### Delete
DELETE {{host}}/crm/v1.0/users/9787e109-5724-4654-b8a9-324fed5326fe
Content-Type: application/json

{
  "updated_by": "4bdf4c46-d7e7-4025-9872-4a28da823209"
}
