basePath: /
definitions:
  code.ErrorMessage:
    properties:
      code:
        description: 回傳代碼
        type: integer
      detailed:
        description: 詳細錯誤內容
      message:
        description: 錯誤回傳訊息
        type: string
      timestamp:
        description: 錯誤時間
        example: "2021-07-29T07:23:47Z"
        type: string
    type: object
  code.SuccessfulMessage:
    properties:
      body:
        description: 正確回傳內容
      code:
        description: 回傳代碼
        type: integer
      timestamp:
        description: 錯誤時間
        example: "2021-07-29T07:23:47Z"
        type: string
    type: object
  customers.Create:
    properties:
      address:
        description: 地址
        type: string
      created_by:
        description: 創建者
        type: string
      eng_name:
        description: 英文名稱
        type: string
      fax:
        description: 傳真
        type: string
      liaison:
        description: 聯絡人
        type: string
      liaison_phone:
        description: 聯絡人手機號碼
        type: string
      mail:
        description: 電子郵件
        type: string
      map:
        description: 地圖
        type: string
      name:
        description: 中文名稱
        type: string
      remark:
        description: 備註
        type: string
      short_name:
        description: 簡稱
        type: string
      tax_id_number:
        description: 統編
        type: string
      tel:
        description: 電話
        type: string
      zip_code:
        description: 郵遞區號
        type: string
    required:
    - address
    - created_by
    - eng_name
    - fax
    - liaison
    - liaison_phone
    - mail
    - map
    - name
    - remark
    - short_name
    - tax_id_number
    - tel
    - zip_code
    type: object
  customers.List:
    properties:
      customers:
        description: 多筆
        items:
          properties:
            address:
              description: 地址
              type: string
            c_id:
              description: 客戶編號
              type: string
            created_by:
              description: 創建者
              type: string
            createdAt:
              description: 創建時間
              type: string
            deletedAt:
              description: 刪除時間
              type: string
            eng_name:
              description: 英文名稱
              type: string
            fax:
              description: 傳真
              type: string
            liaison:
              description: 聯絡人
              type: string
            liaison_phone:
              description: 聯絡人手機號碼
              type: string
            mail:
              description: 電子郵件
              type: string
            map:
              description: 地圖
              type: string
            name:
              description: 中文名稱
              type: string
            remark:
              description: 備註
              type: string
            short_name:
              description: 簡稱
              type: string
            tax_id_number:
              description: 統編
              type: string
            tel:
              description: 電話
              type: string
            updatedAt:
              description: 更新時間
              type: string
            zip_code:
              description: 郵遞區號
              type: string
          type: object
        type: array
      limit:
        description: 筆數(請從1開始帶入,最高上限20)
        type: integer
      page:
        description: 頁數(請從1開始帶入)
        type: integer
      pages:
        description: 總頁數
        type: integer
      total:
        description: 總筆數
        type: integer
    required:
    - limit
    - page
    type: object
  customers.Single:
    properties:
      address:
        description: 地址
        type: string
      c_id:
        description: 客戶編號
        type: string
      created_by:
        description: 創建者
        type: string
      createdAt:
        description: 創建時間
        type: string
      deletedAt:
        description: 刪除時間
        type: string
      eng_name:
        description: 英文名稱
        type: string
      fax:
        description: 傳真
        type: string
      liaison:
        description: 聯絡人
        type: string
      liaison_phone:
        description: 聯絡人手機號碼
        type: string
      mail:
        description: 電子郵件
        type: string
      map:
        description: 地圖
        type: string
      name:
        description: 中文名稱
        type: string
      remark:
        description: 備註
        type: string
      short_name:
        description: 簡稱
        type: string
      tax_id_number:
        description: 統編
        type: string
      tel:
        description: 電話
        type: string
      updatedAt:
        description: 更新時間
        type: string
      zip_code:
        description: 郵遞區號
        type: string
    type: object
  customers.Update:
    properties:
      address:
        description: 地址
        type: string
      eng_name:
        description: 英文名稱
        type: string
      fax:
        description: 傳真
        type: string
      liaison:
        description: 聯絡人
        type: string
      liaison_phone:
        description: 聯絡人手機號碼
        type: string
      mail:
        description: 電子郵件
        type: string
      map:
        description: 地圖
        type: string
      name:
        description: 中文名稱
        type: string
      remark:
        description: 備註
        type: string
      short_name:
        description: 簡稱
        type: string
      tax_id_number:
        description: 統編
        type: string
      tel:
        description: 電話
        type: string
      zip_code:
        description: 郵遞區號
        type: string
    type: object
host: api.testing.whisky.inherited.app
info:
  contact:
    email: mingzong.lyu@gmail.com
    name: API System Support
    url: https://inherited.app/
  description: JG Server API
  license:
    name: AGPL 3.0
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  termsOfService: https://inherited.app/
  title: Whisky SYSTEM API
  version: "0.1"
paths:
  /authority/v1.0/customer:
    get:
      consumes:
      - application/json
      description: 取得全部客戶
      parameters:
      - description: 目前頁數,請從1開始帶入
        in: query
        name: page
        required: true
        type: integer
      - description: 一次回傳比數,請從1開始帶入,最高上限20
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功後返回的值
          schema:
            allOf:
            - $ref: '#/definitions/code.SuccessfulMessage'
            - properties:
                body:
                  $ref: '#/definitions/customers.List'
              type: object
        "415":
          description: 必要欄位帶入錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
        "500":
          description: 伺服器非預期錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
      summary: 取得全部客戶
      tags:
      - customer
    post:
      consumes:
      - application/json
      description: 新增客戶
      parameters:
      - description: 新增客戶
        in: body
        name: '*'
        required: true
        schema:
          $ref: '#/definitions/customers.Create'
      produces:
      - application/json
      responses:
        "200":
          description: 成功後返回的值
          schema:
            allOf:
            - $ref: '#/definitions/code.SuccessfulMessage'
            - properties:
                body:
                  type: string
              type: object
        "415":
          description: 必要欄位帶入錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
        "500":
          description: 伺服器非預期錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
      summary: 新增客戶
      tags:
      - customer
  /authority/v1.0/customer/{cID}:
    delete:
      consumes:
      - application/json
      description: 刪除單一客戶
      parameters:
      - description: 客戶ID
        in: path
        name: cID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功後返回的值
          schema:
            allOf:
            - $ref: '#/definitions/code.SuccessfulMessage'
            - properties:
                body:
                  type: string
              type: object
        "415":
          description: 必要欄位帶入錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
        "500":
          description: 伺服器非預期錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
      summary: 刪除單一客戶
      tags:
      - customer
    get:
      consumes:
      - application/json
      description: 取得單一客戶
      parameters:
      - description: 客戶ID
        in: path
        name: cID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功後返回的值
          schema:
            allOf:
            - $ref: '#/definitions/code.SuccessfulMessage'
            - properties:
                body:
                  $ref: '#/definitions/customers.Single'
              type: object
        "415":
          description: 必要欄位帶入錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
        "500":
          description: 伺服器非預期錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
      summary: 取得單一客戶
      tags:
      - customer
    patch:
      consumes:
      - application/json
      description: 更新單一客戶
      parameters:
      - description: 客戶ID
        in: path
        name: cID
        required: true
        type: string
      - description: 更新客戶
        in: body
        name: '*'
        required: true
        schema:
          $ref: '#/definitions/customers.Update'
      produces:
      - application/json
      responses:
        "200":
          description: 成功後返回的值
          schema:
            allOf:
            - $ref: '#/definitions/code.SuccessfulMessage'
            - properties:
                body:
                  type: string
              type: object
        "415":
          description: 必要欄位帶入錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
        "500":
          description: 伺服器非預期錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
      summary: 更新單一客戶
      tags:
      - customer
schemes:
- https
swagger: "2.0"
