basePath: /
host: api.testing.whisky.inherited.app
info:
  contact:
    email: mingzong.lyu@gmail.com
    name: API System Support
    url: https://inherited.app/
  description: JG Server API
  license:
    name: AGPL 3.0
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  termsOfService: https://inherited.app/
  title: Whisky SYSTEM API
  version: "0.1"
paths: {}
schemes:
- https
swagger: "2.0"
