basePath: /
definitions:
  code.ErrorMessage:
    properties:
      code:
        description: 回傳代碼
        type: integer
      detailed:
        description: 詳細錯誤內容
      message:
        description: 錯誤回傳訊息
        type: string
      timestamp:
        description: 錯誤時間
        example: "2021-07-29T07:23:47Z"
        type: string
    type: object
  code.SuccessfulMessage:
    properties:
      body:
        description: 正確回傳內容
      code:
        description: 回傳代碼
        type: integer
      timestamp:
        description: 錯誤時間
        example: "2021-07-29T07:23:47Z"
        type: string
    type: object
  users.Create:
    properties:
      company_id:
        description: 公司ID
        type: string
      created_by:
        description: 創建者
        type: string
      email:
        description: 電子郵件
        type: string
      name:
        description: 中文名稱
        type: string
      password:
        description: 密碼
        type: string
      phone_number:
        description: 電話
        type: string
      user_name:
        description: 使用者名稱
        type: string
    required:
    - company_id
    - created_by
    - name
    - password
    - user_name
    type: object
  users.List:
    properties:
      limit:
        description: 筆數(請從1開始帶入,最高上限20)
        type: integer
      page:
        description: 頁數(請從1開始帶入)
        type: integer
      pages:
        description: 總頁數
        type: integer
      total:
        description: 總筆數
        type: integer
      users:
        description: 多筆
        items:
          properties:
            company_id:
              description: 公司ID
              type: string
            created_at:
              description: 創建時間
              type: string
            created_by:
              description: 創建者
              type: string
            deleted_at:
              description: 刪除時間
              type: string
            email:
              description: 電子郵件
              type: string
            is_deleted:
              description: 是否刪除
              type: boolean
            name:
              description: 中文名稱
              type: string
            password:
              description: 密碼
              type: string
            phone_number:
              description: 電話
              type: string
            updated_at:
              description: 更新時間
              type: string
            updated_by:
              description: 更新者
              type: string
            user_id:
              description: 使用者ID
              type: string
            user_name:
              description: 使用者名稱
              type: string
          type: object
        type: array
    required:
    - limit
    - page
    type: object
  users.Single:
    properties:
      company_id:
        description: 公司ID
        type: string
      created_at:
        description: 創建時間
        type: string
      created_by:
        description: 創建者
        type: string
      deleted_at:
        description: 刪除時間
        type: string
      email:
        description: 電子郵件
        type: string
      is_deleted:
        description: 是否刪除
        type: boolean
      name:
        description: 中文名稱
        type: string
      password:
        description: 密碼
        type: string
      phone_number:
        description: 電話
        type: string
      updated_at:
        description: 更新時間
        type: string
      updated_by:
        description: 更新者
        type: string
      user_id:
        description: 使用者ID
        type: string
      user_name:
        description: 使用者名稱
        type: string
    type: object
  users.Update:
    properties:
      company_id:
        description: 公司ID
        type: string
      email:
        description: 電子郵件
        type: string
      name:
        description: 中文名稱
        type: string
      password:
        description: 密碼
        type: string
      phone_number:
        description: 電話
        type: string
      updated_by:
        description: 更新者
        type: string
      user_name:
        description: 使用者名稱
        type: string
    required:
    - updated_by
    type: object
host: api.testing.whisky.inherited.app
info:
  contact:
    email: eirc8888@gmail.com
    name: API System Support
    url: https://inherited.app/
  description: CRM API
  license:
    name: AGPL 3.0
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  termsOfService: https://inherited.app/
  title: CRM API
  version: "0.1"
paths:
  /authority/v1.0/user:
    get:
      consumes:
      - application/json
      description: 取得全部使用者
      parameters:
      - description: JWE Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 目前頁數,請從1開始帶入
        in: query
        name: page
        required: true
        type: integer
      - description: 一次回傳比數,請從1開始帶入,最高上限20
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功後返回的值
          schema:
            allOf:
            - $ref: '#/definitions/code.SuccessfulMessage'
            - properties:
                body:
                  $ref: '#/definitions/users.List'
              type: object
        "415":
          description: 必要欄位帶入錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
        "500":
          description: 伺服器非預期錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
      summary: 取得全部使用者
      tags:
      - user
    post:
      consumes:
      - application/json
      description: 新增使用者
      parameters:
      - description: JWE Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 新增使用者
        in: body
        name: '*'
        required: true
        schema:
          $ref: '#/definitions/users.Create'
      produces:
      - application/json
      responses:
        "200":
          description: 成功後返回的值
          schema:
            allOf:
            - $ref: '#/definitions/code.SuccessfulMessage'
            - properties:
                body:
                  type: string
              type: object
        "415":
          description: 必要欄位帶入錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
        "500":
          description: 伺服器非預期錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
      summary: 新增使用者
      tags:
      - user
  /authority/v1.0/user/{userID}:
    delete:
      consumes:
      - application/json
      description: 刪除單一使用者
      parameters:
      - description: JWE Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 使用者ID
        in: path
        name: userID
        required: true
        type: string
      - description: 更新使用者
        in: body
        name: '*'
        required: true
        schema:
          $ref: '#/definitions/users.Update'
      produces:
      - application/json
      responses:
        "200":
          description: 成功後返回的值
          schema:
            allOf:
            - $ref: '#/definitions/code.SuccessfulMessage'
            - properties:
                body:
                  type: string
              type: object
        "415":
          description: 必要欄位帶入錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
        "500":
          description: 伺服器非預期錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
      summary: 刪除單一使用者
      tags:
      - user
    get:
      consumes:
      - application/json
      description: 取得單一使用者
      parameters:
      - description: JWE Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 使用者ID
        in: path
        name: userID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功後返回的值
          schema:
            allOf:
            - $ref: '#/definitions/code.SuccessfulMessage'
            - properties:
                body:
                  $ref: '#/definitions/users.Single'
              type: object
        "415":
          description: 必要欄位帶入錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
        "500":
          description: 伺服器非預期錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
      summary: 取得單一使用者
      tags:
      - user
    patch:
      consumes:
      - application/json
      description: 更新單一使用者
      parameters:
      - description: JWE Token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 使用者ID
        in: path
        name: userID
        required: true
        type: string
      - description: 更新使用者
        in: body
        name: '*'
        required: true
        schema:
          $ref: '#/definitions/users.Update'
      produces:
      - application/json
      responses:
        "200":
          description: 成功後返回的值
          schema:
            allOf:
            - $ref: '#/definitions/code.SuccessfulMessage'
            - properties:
                body:
                  type: string
              type: object
        "415":
          description: 必要欄位帶入錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
        "500":
          description: 伺服器非預期錯誤
          schema:
            allOf:
            - $ref: '#/definitions/code.ErrorMessage'
            - properties:
                detailed:
                  type: string
              type: object
      summary: 更新單一使用者
      tags:
      - user
schemes:
- https
swagger: "2.0"
